# Build stage
FROM node:20.13.0-alpine AS build
WORKDIR /app
COPY package*.json /app
RUN npm ci
COPY . .
RUN npm run build

# Serve stage
FROM nginx:alpine
COPY nginx.conf /etc/nginx
COPY --from=build /app/dist/* /usr/share/nginx/html
EXPOSE 80 443
