version: "3"

name: grassway-app-development

services:
  client:
    container_name: client-dev
    build:
      context: ./client
      dockerfile: Dockerfile.dev
    volumes:
      - ./client:/app
      - /app/node_modules
    ports:
      - 4200:4200 
    networks:
      - devnet
    depends_on:
      - server

  server:
    container_name: server-dev
    build:
      context: ./server
      dockerfile: Dockerfile.dev
    volumes:
      - ./server:/app
      - /app/node_modules
      - server-data:/app/resources 
    ports:
      - 3000:3000
    networks:
      - devnet
    depends_on:
      database:
        condition: service_healthy
      redis:
        condition: service_healthy

  database: 
    container_name: database-dev
    image: postgres:alpine
    volumes:
      - db-data:/var/lib/postgresql/data
    ports:
      - 5433:5432
    env_file:
      - .database-env.development
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 1s
      timeout: 20s
      retries: 5
      start_period: 30s  
    networks:
      - devnet
  
  redis:
    container_name: redis-dev
    image: redis:alpine
    volumes:
      - redis-data:/data
    ports:
      - 6389:6379
    healthcheck:
      test: ["CMD", "redis-cli","ping"]
      interval: 1s
      timeout: 20s
      retries: 5
      start_period: 30s  
    networks:
      - devnet

networks:
  devnet:

volumes:
  server-data:
  db-data:
  redis-data: